{"name": "test_a", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_pytestjob.Test_one object at 0x0000011ED0765B70>\n\n    def test_a(self):\n        print('------我是第一个pytest程序----------')\n>       assert 1==2\nE       assert 1 == 2\n\ntest_pytestjob.py:13: AssertionError"}, "attachments": [{"name": "stdout", "source": "0b0f9715-c3e6-4f8d-8b27-02666e62c01e-attachment.txt", "type": "text/plain"}], "start": 1600330391187, "stop": 1600330391188, "uuid": "46a8b924-cdee-43b2-ab16-085e2da4fea9", "historyId": "f8a8e317057407b7e4f6cc6b226ebdbe", "testCaseId": "378561f9864041fe9fa859f93933b030", "fullName": "test_pytestjob.Test_one#test_a", "labels": [{"name": "suite", "value": "test_pytestjob"}, {"name": "subSuite", "value": "Test_one"}, {"name": "host", "value": "LAPTOP-CT29F0O2"}, {"name": "thread", "value": "13300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytestjob"}]}